# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        
        # login area for backoffice users
        backoffice:
            context: primary_auth
            pattern:            ^/backoffice
            form_login:
                provider:       fos_userbundle
                login_path:     course_back_office_security_login
                use_forward:    true
                use_referer:    true
                check_path:     course_back_office_security_check
                failure_path:   course_back_office_security_login
                default_target_path: course_back_office_homepage
            logout:
                path: course_back_office_security_logout
                target: course_cms_bundle_homepage
            anonymous:    true

    access_control:
            # back-office
            - { path: ^/backoffice/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/backoffice, roles: ROLE_ADMIN }